# Generated by Django 5.1.6 on 2025-04-09 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enter_date', models.DateField()),
                ('aprov_date', models.DateField(blank=True, null=True)),
                ('curso', models.CharField(blank=True, max_length=4, null=True)),
                ('departamento', models.CharField(blank=True, max_length=4, null=True)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('matricula', models.CharField(blank=True, max_length=10, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('siape', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField()),
                ('telefone', models.CharField(max_length=15, unique=True)),
                ('tipo_usuario', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'account_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(blank=True, null=True, unique=True)),
                ('curso', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id_consumo', models.AutoField(primary_key=True, serialize=False)),
                ('data_consumo', models.DateField(blank=True, null=True)),
                ('motivo_uso', models.TextField(blank=True, null=True)),
                ('qtd_consumida', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_departamento', models.TextField()),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id_emprestimo', models.AutoField(primary_key=True, serialize=False)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('data_emprestimo', models.DateField()),
            ],
            options={
                'db_table': 'emprestimo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_admin', models.BooleanField(blank=True, null=True)),
                ('nome', models.TextField()),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('tipo_user', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id_inst', models.AutoField(primary_key=True, serialize=False)),
                ('nome_inst', models.TextField()),
            ],
            options={
                'db_table': 'instituicao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siare', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'professor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siare', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'servidor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Externo',
            fields=[
                ('id_user', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.usuario')),
            ],
            options={
                'db_table': 'externo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumo',
            fields=[
                ('id_item', models.OneToOneField(db_column='id_item', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.item')),
                ('qtd', models.IntegerField(blank=True, null=True)),
                ('data_registro', models.DateField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'material_consumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialPermanente',
            fields=[
                ('id_item', models.OneToOneField(db_column='id_item', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.item')),
                ('data_baixa', models.DateField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('id_patrimonio', models.TextField(blank=True, null=True, unique=True)),
                ('situacao', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'material_permanente',
                'managed': False,
            },
        ),
    ]
