# Generated by Django 5.1.6 on 2025-04-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permicao',
            fields=[
                ('id_permicao', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permicao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permicao_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permicoes',
                'managed': False,
            },
        ),
    ]
