# Generated by Django 5.1.6 on 2025-03-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='enter_date',
            field=models.DateField(),
        ),
    ]
