# Generated by Django 5.1.6 on 2025-03-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_enter_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='aprov_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de aprovação'),
        ),
        migrations.AddField(
            model_name='account',
            name='cell_number',
            field=models.CharField(default='(000)99999-9999', max_length=15, unique=True, verbose_name='(DDD)99999-9999'),
        ),
        migrations.AddField(
            model_name='account',
            name='course',
            field=models.CharField(blank=True, choices=[('ENC', 'ENC'), ('ENE', 'ENE'), ('TIC', 'TIC'), ('MED', 'MED'), ('FT', 'FT')], max_length=4, null=True, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='account',
            name='departament',
            field=models.CharField(blank=True, choices=[('DEC', 'DEC'), ('CIT', 'CIT'), ('DCM', 'DCM'), ('DCS', 'DCS'), ('DFT', 'DFT'), ('EES', 'EES'), ('FQM', 'FQM')], max_length=4, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='admin@admin.com', max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='account',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='fulano', max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_fotos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='account',
            name='siape',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='enter_date',
            field=models.DateField(auto_now_add=True, verbose_name='data de inscrição'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type_of_user',
            field=models.CharField(choices=[('aluno', 'aluno'), ('professor', 'professor'), ('servidor', 'servidor'), ('externo', 'externo')], max_length=9, verbose_name='Vinculo'),
        ),
    ]
