# Generated by Django 5.1.6 on 2025-03-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_aprov_date_account_cell_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(choices=[('Sim', True), ('Não', False)], default=False, verbose_name='Usuario ativo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cell_number',
            field=models.CharField(default='(000)99999-9999', max_length=15, unique=True, verbose_name='Telefone'),
        ),
    ]
