# Generated by Django 5.1.6 on 2025-03-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_is_active_alter_account_cell_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='course',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='departament',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='photo',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cell_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='type_of_user',
        ),
        migrations.AddField(
            model_name='account',
            name='telefone',
            field=models.CharField(default='(999)99999-9999', max_length=15, unique=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='account',
            name='tipo_usuario',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor'), ('servidor', 'Servidor'), ('externo', 'Externo')], default='aluno', max_length=9, verbose_name='Vinculo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default='default@default.com', max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Usuario ativo'),
        ),
    ]
