# Generated by Django 5.1.6 on 2025-04-09 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_course_account_curso_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
